### ISSUE TITLE
Ошибка команды /op

### ISSUE THREAD

**Issue by Rconov** [LiteCoreTeam/LiteCore-public#3]
### Описание ошибки
Хотел выдать права оператора на оффлайн ник, в итоге прилетел крашДамп

### Шаги для воспроизведения ошибки
1. Зашел в консоль
2. Прописал команду op rconov1
[CrashDump_Sun_Sep_29-13.55.15-MSK_2024.log](https://github.com/user-attachments/files/17178966/CrashDump_Sun_Sep_29-13.55.15-MSK_2024.log)

### Операционная система и версия
* Версия ядра: 1.1.0.5-release
* Версия PHP: 8.0.25
* Операционная система сервера: Ubuntu22.04
* Версия игры: PE / Win10
* Операционная система игры: Android

### Crashdump, backtrace или другие файлы
Пожалуйста, прикрепите файлы которые смогут помочь в решении вашей проблемы (скриншоты, крашдампы, стэктрейсы).
ВНИМАНИЕ! Если у Вас не скриншот и не файл, а просто текст, вставьте его между двумя "```"

**Comment by zxcfox** [comment]
.
